language: java
jdk: 
- oraclejdk7
- openjdk6

script: mvn verify

# deploy if the first job is successful; should be replaced by an after_all_success if travis finally supports it
after_success: 
- if [[ $TRAVIS_JOB_NUMBER == *1 ]]; then mvn -DskipTests deploy --settings deploysettings.xml; fi

env: 
  global: 
  - secure: S8VuAFqjAeynvVpHKey0ps2bsXB8WerCrxStIDwUdZY0eMM9awTHnIk/lHyWS2BSO9O6/4T3qjDjfsf90A8jRKjGYoLh4RhQORHiUWm8N71sSiGqHBk7S+vLGx/neAmEK2Mp26CfmGHhMfz6RKQXam2wG6fVO86Kz/GE7lsoQJs=
  - secure: LhVeljhRz0OLm3DBX2Yu+fYg4P0jmxizF0BUEf6Zu7NTOtICDnW+0j/yrCBa6BmGb7EbPqhOqF+SZeUTVqUrAXLV9hQtRLYO/m2QBPVz+aWD9UHm+yJoY59dHvK8p5Gyo1K/xNYzpn/MeeTlgKwIwlbRNUVUXbxWt7hd0iHTo4M=


